apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-generator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-generator
  template:
    metadata:
      labels:
        app: data-generator
    spec:
      containers:
      - name: generator
        image: spark-processor:latest
        command: ["python", "/opt/spark/apps/main.py", "generate", "--rate-mb", "50"]
        env:
        - name: KAFKA_SERVERS
          value: "kafka:9092"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
